[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "ffmpeg", "libsndfile"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["python -m pip install --upgrade pip && python -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --threads 4 --worker-class gthread --log-level info"
