services:
  - type: web
    name: analify
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg libsndfile1
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --log-level info
